python3: can't open file '/mnt/chromeos/removable/COLLECTIVE/github_sync_clean/lucian_self_verification.py': [Errno 2] No such file or directory
